-- 销售单明细支持无缸号：batch_id 未传时存 NULL，不再使用 id=0 占位行。
-- 执行以下语句使 batch_id、batch_code 允许 NULL（若表结构当前为 NOT NULL）：
--
-- ALTER TABLE sales_order_items
--   MODIFY COLUMN batch_id BIGINT NULL,
--   MODIFY COLUMN batch_code VARCHAR(50) NULL DEFAULT '';
